"""create users patients studies tables

Revision ID: cba34ab26ea8
Revises: 
Create Date: 2026-08-06 12:28:52.607266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba34ab26ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=128), nullable=True, comment='Medical Record Number (mock)'),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_patients_mrn', 'patients', ['mrn'], unique=False)
    op.create_index('idx_patients_name', 'patients', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('studies',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=True, comment='DICOM Study Instance UID'),
    sa.Column('accession_number', sa.String(length=128), nullable=True, comment='Hospital accession number'),
    sa.Column('modality', sa.String(length=32), nullable=True, comment='CR, DX, CT, MR, US, etc.'),
    sa.Column('body_part', sa.String(length=128), nullable=True),
    sa.Column('study_description', sa.Text(), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='created, uploaded, processing, ready, failed, archived'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='manual, dicom_upload, mock'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='DICOM tags or custom metadata'),
    sa.Column('storage_path', sa.Text(), nullable=True, comment='Path to stored DICOM files'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_studies_created_by', 'studies', ['created_by_user_id'], unique=False)
    op.create_index('idx_studies_date', 'studies', ['study_date'], unique=False)
    op.create_index('idx_studies_modality', 'studies', ['modality'], unique=False)
    op.create_index('idx_studies_patient_id', 'studies', ['patient_id'], unique=False)
    op.create_index('idx_studies_status', 'studies', ['status'], unique=False)
    op.create_index('idx_studies_uid_unique', 'studies', ['study_instance_uid'], unique=True, postgresql_where=sa.text('study_instance_uid IS NOT NULL'))
    op.create_index(op.f('ix_studies_accession_number'), 'studies', ['accession_number'], unique=False)
    op.create_index(op.f('ix_studies_created_by_user_id'), 'studies', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_studies_modality'), 'studies', ['modality'], unique=False)
    op.create_index(op.f('ix_studies_patient_id'), 'studies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_index(op.f('ix_studies_study_date'), 'studies', ['study_date'], unique=False)
    op.create_index(op.f('ix_studies_study_instance_uid'), 'studies', ['study_instance_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_study_instance_uid'), table_name='studies')
    op.drop_index(op.f('ix_studies_study_date'), table_name='studies')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_index(op.f('ix_studies_patient_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_modality'), table_name='studies')
    op.drop_index(op.f('ix_studies_created_by_user_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_accession_number'), table_name='studies')
    op.drop_index('idx_studies_uid_unique', table_name='studies', postgresql_where=sa.text('study_instance_uid IS NOT NULL'))
    op.drop_index('idx_studies_status', table_name='studies')
    op.drop_index('idx_studies_patient_id', table_name='studies')
    op.drop_index('idx_studies_modality', table_name='studies')
    op.drop_index('idx_studies_date', table_name='studies')
    op.drop_index('idx_studies_created_by', table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index('idx_patients_name', table_name='patients')
    op.drop_index('idx_patients_mrn', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
